//covering_code.cpp ~ Implementation of covering_code.h

#include "covering_code.h"

bool increment(Assignment& Values){//Considers the values of an assignment as the digits of a binary integer, increments that integer by one and returns true if maximal binary integer with n digits is not reached
	bool out = true;
	bool t2f = true;//the information whether the previous variable waas changed from true to false
	int iterator = 0;
	int num_var = Values.num_var();
	while(t2f and num_var > iterator){
		if(Values.get(iterator)){
			Values.set(iterator,false);
			iterator++;
		}
		else{
			Values.set(iterator,true);
			t2f = false;
		}
	}
	if(iterator == num_var){out = false;}
	return out;
}

bool increase1(std::vector<unsigned int>& numbers, const unsigned int p){
	unsigned int n = numbers.size();
	bool out = true;
	bool changed_2_0 = true;//the information whether the previous digit was changed from p-1 to 0
	unsigned int iterator = 0;
	while(changed_2_0 and iterator < n){
		if(numbers[iterator] > p - 1){throw std::runtime_error("Digit has value higher than p!");}
		if(numbers[iterator] == p - 1){
			numbers[iterator] = 0;
			iterator++;
		}
		else{
			numbers[iterator]++;
			changed_2_0 = false;
		}
	}
	if(iterator == n){out = false;}
	return out;
}

unsigned int distance(const Assignment& asgn1, const Assignment& asgn2){
	unsigned int n1 = asgn1.num_var();
	unsigned int n2 = asgn2.num_var();
	if(n1 != n2){throw std::runtime_error("Size of Assignments do not match!\n");}
	unsigned int out = 0;
	for(unsigned int i = 0; i < n1; i++){
		if(asgn1.get(i) != asgn2.get(i)){out++;}
	}
	return out;
}

bool is_covered(const Code& cover, const Assignment& asgn, const unsigned int& r){
	bool out = false;
	for(Assignment a : cover){
		if(distance(a,asgn) <= r){
			out = true;
			break;
		}
	}
	return out;
}

Code small_cover(const unsigned int n, const unsigned int r){//returns a covering code of length n and radius r using Lemma 5
	Code cover;
	//coverings for radius >= n / 2
	if(r * 2 >= n){
		std::vector<bool> vec1(n,false);
		std::vector<bool> vec2(n,true);
		Assignment center1(vec1);
		Assignment center2(vec2);
		cover.push_back(center1);
		cover.push_back(center2);
		return cover;
	}

	//coverings for radius < n / 2 generated by a greedy algorithm in poly(n) * 2^(3 * n) time
	std::vector<bool> values(n,false);//defined here to improve time efficiency
	bool terminate = false;
	while(not terminate){
		//std::vector<bool> values(n,false); defined outside of loop to improve time efficiency
		Assignment candidate(values);//new candidate for the covering
		Assignment current(values);//assignment over which we will iterate
		
		unsigned int new_cvrd = 0;//number of assignments that were not covered but got covered by the assignment "candidate"
		bool not_yet = true;
		
		while(not_yet){//count all assignments that were previously not covered, but get covered by candidate
			//create an assignment to check if it is covered
			//then move to a next assignment untill all assignments have been covered
			unsigned int num = 0;//number of assignments that were not covered but got covered by the assignment "current"
			bool not_covered_all = true;//there are still assignments to check
			
			std::vector<bool> values_(n,false);
			Assignment testing(values_);//we will check if this was previously not covered but gets covered by the inclusion of "current"
			
			while(not_covered_all){
				bool condition1 = not is_covered(cover,testing,r);//previously not covered
				bool condition2 = distance(testing,current) <= r;//gets covered by the inclusion of "current"
				if(condition1 and condition2){num++;}
				not_covered_all = increment(testing);//move to next assignment
			}
			
			if(new_cvrd < num){//current is better than candidate
				new_cvrd = num;
				candidate = current;
			}
			not_yet = increment(current);
		}
		if(new_cvrd == 0){terminate = true;}
		else{cover.push_back(candidate);}
	}
	return cover;
}
